description = "Alan个人笔记文档"
# 网站关键词
keywords = ["alan", "Hugo", "devops"]
# 应用图标配置
[app]
  # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
  title = "Alan"
  # 是否隐藏网站图标资源链接
  noFavicon = false
  # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
  svgFavicon = "/images/favicon-32x32.png"
  # Safari 图标颜色
  iconColor = "#5bbad5"
  # Windows v8-10 磁贴颜色
  tileColor = "#da532c"

# 搜索配置
[search]
  enable = false

# 主页信息设置
[home]
  # RSS 文章数目
  rss = 12
  # 主页个人信息
  [home.profile]
    enable = true
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    avatarURL = "/images/avatar.png"
    # 头像的链接指向的 URL
    avatarLinkURL = ""
    # 主页显示的网站标题 (支持 HTML 格式)
    title = ""
    # 主页显示的网站副标题
    subtitle = "梦，开始的地方"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = true
    # 免责声明 (支持 HTML 格式)
    disclaimer = ""

  # 主页文章列表
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    # 主页每页显示文章数量
    paginate = 12

# 主页的社交信息设置
[social]
  Angellist = ""
  Bandcamp = ""
  Behance = ""
  Bilibili = ""
  Bitbucket = ""
  BuyMeACoffee = ""
  Codepen = ""
  Deviantart = ""
  Devto = ""
  Douban = ""
  Dribbble = ""
  Email = "al6nlee@163.com"
  Facebook = ""
  Fivehundredpx = ""
  Flickr = ""
  Foursquare = ""
  FreeCodeCamp = ""
  Gitea = ""
  GitHub = "al6nlee"
  Gitlab = ""
  Goodreads = ""
  Googlescholar = ""
  Hackernews = ""
  Instagram = ""
  Jsfiddle = ""
  Keybase = ""
  Kickstarter = ""
  Ko-Fi = ""
  Lastfm = ""
  Liberapay = ""
  Linkedin = ""
  Linktree = ""
  Mastodon = ""
  Matrix = ""
  Medium = ""
  Mix = ""
  Odnoklassniki = ""
  ORCID = ""
  Patreon = ""
  Paypal = ""
  Pinterest = ""
  QQ = ""
  QQGroup = ""
  Quora = ""
  Reddit = ""
  Researchgate = ""
  RSS = true
  Skype = ""
  Slidershare = ""
  Snapchat = ""
  Soundcloud = ""
  Spotify = ""
  Stackoverflow = ""
  Steam = ""
  Strava = ""
  Telegram = ""
  Thingiverse = ""
  Tumblr = ""
  Twitch = ""
  Twitter = ""
  Vine = ""
  VK = ""
  Weibo = ""
  Whatsapp = ""
  Wordpress = ""
  Xing = ""
  XMPP = ""
  Youtubechannel = ""
  Youtubecustom = ""
  Youtubelegacy = ""
  Zhihu = ""
  [social.Diaspora]
    id = "@xxxx"
    prefix = "https://yyyy/"

# 文章页面配置
[page]
  # 是否在主页隐藏一篇文章
  hiddenFromHomePage = false
  # 是否在搜索结果中隐藏一篇文章
  hiddenFromSearch = false
  # 是否使用 twemoji
  twemoji = false
  # 是否使用 lightgallery
  lightgallery = false
  # 是否使用 ruby 扩展语法
  ruby = true
  # 是否使用 fraction 扩展语法
  fraction = true

  # 是否显示原始 Markdown 文档内容的链接
  linkToMarkdown = true
  # 配置文章原始文件的链接
  linkToSource = ""
  # "https://github.com/user/repo/blob/main/{path}"
  # 配置编辑文章的链接
  linkToEdit = ""
  # https://github.com/user/repo/edit/main/{path}
  # https://gitlab.com/user/repo/-/edit/main/{path}
  # https://bitbucket.org/user/repo/src/main/{path}?mode=edit
  # 配置提交错误的链接
  linkToReport = ""
  # https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
  # https://gitlab.com/user/repo/-/issues/new?issue[title]=[bug]%20{title}&issue[description]=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://gitlab.com/user/repo/-/edit/main/{path}|
  # 是否在 RSS 中显示全文内容
  rssFullText = false
  # 是否使用系列导航
  seriesNavigation = true
  # 是否启用最后修改时间
  enableLastMod = true
  # 是否启用字数统计
  enableWordCount = true
  # 是否启用阅读时间估计
  enableReadingTime = true
  # 在文章开头显示提示信息，提醒读者文章内容可能过时。
  # instant.page config
  [page.instantpage]
    enable = true
  [page.outdatedArticleReminder]
    enable = false
    # 如果文章最后更新于这天数之前，显示提醒
    reminder = 90
    # 如果文章最后更新于这天数之前，显示警告
    warning = 180
  # 目录配置
  [page.toc]
    # 是否使用目录
    enable = true
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # 是否使侧边目录自动折叠展开
    auto = false
  # 代码配置
  [page.code]
    # 是否显示代码块的复制按钮
    copy = true
    # 默认展开显示的代码行数
    maxShownLines = 24
  # 表格配置
  [page.table]
    # 是否开启表格排序
    sort = true
  [page.header]
    # 是否开启标题自动编号
    [page.header.number]
      enable = true
      [page.header.number.format]
        h2 = "{h2} {title}"
        h3 = "{h2}.{h3} {title}"
        h4 = "{h2}.{h3}.{h4} {title}"
        h5 = "{h2}.{h3}.{h4}.{h5} {title}"
        h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
  # KaTeX 数学公式配置 (KaTeX https://katex.org/)
  [page.math]
    enable = false
    # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # 默认行内定界符是 $ ... $ 和 \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX 插件 mhchem
    mhchem = true
  # Mapbox GL JS 配置 (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
  [page.mapbox]
    # Mapbox GL JS 的 access token
    accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
    # 浅色主题的地图样式
    lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
    # 深色主题的地图样式
    darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
    # 是否添加 NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
    navigation = true
    # 是否添加 GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
    geolocate = true
    # 是否添加 ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
    scale = true
    # 是否添加 FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
    fullscreen = true
  # 文章页面的分享信息设置
  [page.share]
    enable = false
    Baidu = false
    Blogger = false
    Buffer = false
    Digg = false
    Evernote = false
    Facebook = true
    Flipboard = false
    HackerNews = true
    Instapaper = false
    Line = true
    Linkedin = false
    Mix = false
    Myspace = false
    Odnoklassniki = false
    Pinterest = false
    Pocket = false
    Reddit = false
    Renren = false
    Skype = false
    Stumbleupon = false
    Telegram = true
    Trello = false
    Tumblr = false
    Twitter = true
    VK = false
    Weibo = true
    # Weixin API example: "https://tenapi.cn/qr/?txt="
    # https://docs.tenapi.cn/qrcode.html
    # https://www.free-api.com/doc/531
    # http://www.alapi.cn/api/view/72
    # OR self-hosted: https://github.com/yhf7952/QrCodeApi
    Weixin = ""
    Whatsapp = false
    Xing = false
    Mastodon = true

  # Related content config
  # 相关文章推荐配置
  [page.related]
    enable = false
    count = 5